name: Build

on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest
    name: Build with Docker using BlocksDS
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install missing dependencies
        run: wf-pacman -Sy --noconfirm wf-tools
      - name: Make application
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: akmenu2_fat.nds
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            akmenu2_fat.nds
